### ISSUE TITLE
Update readthedocs

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/oiflib#33]
- [x] Add installation section
- [x] Add usage/tutorial section
- [x] Add MIT licence

**Comment by EFT-Defra** [comment]
Post code review conversation with @clarebetts-code booked in for 2021-02-26.
